version: "3"
services:
  type:
    container_name: type-backend
    image: type:latest
    restart: on-failure
    build: .
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
    command: npm run start
    volumes:
      - app-data:/type

  database:
    image: postgres:latest
    container_name: type-database
    restart: on-failure
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: type-prod
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  app-data:
  db-data: 